package enviando.mail;

 import java.util.Properties;
 import javax.mail.Message;
 import javax.mail.MessagingException;
 import javax.mail.PasswordAuthentication;
 import javax.mail.Session;
 import javax.mail.Transport;
 import javax.mail.internet.InternetAddress;
 import javax.mail.internet.MimeMessage;
 public class TesteEmail
 {
 public static void main( String[] args )
 {
 // Put recipient’s address
 String to = "rcm_reinas@hotmail.com";
 // Put sender’s address
 String from = "reinaldo.mendes@sapo.pt";
 final String username = "reinaldo.mendes@sapo.pt";//username generated by Pepipost
 final String password = "Rcmreinas1";//password generated by Pepipost
 // Paste host address from the SMTP relay tab in Integrations from your Pepipost App
 String host = "smtp.sapo.pt";
 Properties  properties = new Properties();
 properties.put("mail.smtp.host", host);
 properties.put("mail.smtp.port", "465");
 properties.put("mail.smtp.ssl.enable", "true");
 properties.put("mail.smtp.auth", "true");
 // Get the Session object.
 Session session = Session.getInstance( properties,
 new javax.mail.Authenticator() {
 protected PasswordAuthentication getPasswordAuthentication() {
 return new PasswordAuthentication(username, password);
 }
 });
 session.setDebug(true);
 try {
 // Create a default MimeMessage object.
 Message message = new MimeMessage(session);
 // Set From: header field
 message.setFrom(new InternetAddress(from));
 // Set To: header field
 message.setRecipients(Message.RecipientType.TO,
 InternetAddress.parse(to));
 // Set Subject: header field
 message.setSubject("My first message with JavaMail");
 // Put the content of your message
 message.setText("Hi there, this is my first message sent with JavaMail");
 // Send message
 System.out.println("Sending msg");
 Transport.send(message);
 System.out.println("Sent message successfully....");
 } catch (MessagingException e) {
 throw new RuntimeException(e);
 }
 }
 }